name: Build All Platforms

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-13, ubuntu-latest] # Adjusted macos version for Intel x64 target

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      # Run Windows build only on Windows runner
      - name: Build app (Windows)
        if: matrix.os == 'windows-latest'
        run: npm run build

      # Run Mac build only on Mac runner
      - name: Build app (macOS)
        if: matrix.os == 'macos-13'
        run: npm run build:mac

      # Run Linux build only on Linux runner
      - name: Build app (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: npm run build:linux

      # Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-artifacts
          path: dist/*
